# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.3.2
      hooks:
          # Disabled becaue it can't detect function use in doctests.
          # # Run the linter.
          # - id: ruff
          #   args: [--fix]
          # Run the formatter.
          - id: ruff-format

default_language_version:
    python: python3.10
