[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules --doctest-continue-on-failure"
doctest_optionflags = "NORMALIZE_WHITESPACE"

[tool.ruff]
lint.ignore = ["E501"]
lint.select = ["E", "F", "I", "W"]
lint.fixable = ["E", "F", "I"]
exclude = [".env", ".venv", "venv", "notebooks"]
output-format = "full"
