[tool.black]
line-length = 180
target-version = ['py310']
include = '\.py'

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules --doctest-continue-on-failure"

[tool.pylint]
    [tool.pylint.'MESSAGES CONTROL']
    max-line-length = 180
    disable = ['C0103,R0903,E0102,C0116,C0302,C0115']
